# Generated by Django 6.1.1 on 2026-09-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('payment_method', models.CharField(choices=[('MB_eBanking', 'MB eBanking'), ('ShopeePay', 'ShopeePay'), ('ZaloPay', 'ZaloPay'), ('MoMo', 'MoMo')], default='MB_eBanking', max_length=20, verbose_name='Phương thức thanh toán')),
                ('shipping_provider', models.CharField(choices=[('SPX_Express', 'SPX Express'), ('J_and_T_Express', 'J&T Express'), ('GHTK', 'GHTK')], default='SPX_Express', max_length=20, verbose_name='Đơn vị vận chuyển')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('completed', 'Hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-pk'],
            },
        ),
    ]
